---
#title           :rawInstanceCreate_global.yml
#description     :This Ansible playbook  will create ECS from Image which we created
#author          :Abhay Srivastava
#date            :2019/01/07
#version         :0.1
#notes           :Install Vim and Emacs to use this playbook.
#==============================================================================


- hosts: localhost
  vars_files:
    - /opt/abhay/project/globalImageFactory/vars/var_stuff.yml 
  tasks:

  - name: Check file exists or not
    stat: path=/opt/abhay/project/globalImageFactory/{{ instance_name }}/rawInstanceCreate_global_success
    register: success_file

  - name: End play if success file already exists
    meta: end_play
    when: success_file.stat.exists

  - name: Creating instance from image
    shell: /bin/openstack --insecure server create --flavor t2.micro --image {{ image_name }} \
             --key-name mykey-$instance_name --nic net-id=1fd7a904-2367-4a43-ae49-1351588387d6 \
             --security-group default {{ instance_name }}

  - name: Sleeping for 30 seconds
    shell: sleep 30

  - name: Checking status of instance
    shell: openstack server  show {{ instance_name }}  | grep power_state | awk -F "|" '{print $3}'
    register: ins_stat
    until: ins_stat.stdout[1:8].find("Running") != -1
    retries: 50
    delay: 30

  - name: Stopping instance
    shell: openstack server stop {{ instance_name }}
    ignore_errors: yes

  - name: Sleeping for 1 min
    shell: sleep 60

  - name: Starting instance
    shell: openstack server start {{ instance_name }}
    ignore_errors: yes

  - name: Sleeping for 1 min
    shell: sleep 60

  - name: Checking status of instance
    shell: openstack server  show {{ instance_name }}  | grep power_state | awk -F "|" '{print $3}'
    register: ins_stat_n
    until: ins_stat_n.stdout[1:8].find("Running") != -1

  - name: Creating success file
    file:
      path: /opt/abhay/project/globalImageFactory/{{ instance_name }}/rawInstanceCreate_global_success
      state: touch
